// Names of the infocard sprite files under public/assets/icons/ (the
// InfocardConfig icon set). Used by the tag-icon picker; resolve to URLs with
// assets.ts `iconUrl`. Mirror this list when scripts/extract-assets.mjs adds
// or removes icons.
export const TAG_ICON_NAMES: string[] = [
  'APS',
  'Ability_Radar',
  'Afterburner',
  'Agility turn rate.air',
  'Agility turn rate.hel',
  'Amphibious',
  'Anti-radar Icon',
  'Armor',
  'Cluster Ammo Icon',
  'Countermeasures',
  'Countermeasures.air',
  'Countermeasures.hel',
  'ECM',
  'Explosive charge',
  'FM_Ammo_Smoke',
  'Forward speed.air',
  'Forward speed.car',
  'Forward speed.hel',
  'Forward speed.inf',
  'Fuel',
  'HEAT',
  'HEAT Armor Icon',
  'Health points.car',
  'Health points.inf',
  'Kinetic',
  'Kinetic Armor Icon',
  'Laser designation',
  'Load capacity',
  'Loading Icon',
  'Mini drone',
  'Mobility Icon',
  'Modification Armor Slot Icon',
  'Modification Icon',
  'Napalm Icon',
  'Optics',
  'Optics Icon',
  'Order_Stop',
  'Points Icon',
  'Seats',
  'Smoke screen',
  'Speed backwards.car',
  'Sprint',
  'Stay hidden',
  'Stealth',
  'Target Type Aircrafts Icon',
  'Target Type Helicopters Icon',
  'Target Type Infantry Icon',
  'Target Type Missiles Icon',
  'Target Type Vehicles Icon',
  'Targeting Icon',
  'Top Attack Type Icon',
  'Weight',
  'airdrop',
  'ammo type',
  'anti-car',
  'anti-down.air',
  'anti-up.air',
  'collapse',
  'damage',
  'deployment',
  'effective range',
  'expand',
  'group',
  'penetration',
  'pin',
  'pinned',
  'reload',
]

/** Prettify a sprite filename for display, e.g. "Forward speed.car" → "Forward speed". */
export function prettyIconName(name: string): string {
  return name.replace(/\.[a-z]+$/i, '').replace(/ Icon$/i, '').replace(/_/g, ' ')
}
